CREATE DATABASE `ejerciciocarros4255`;
USE `ejerciciocarros`;
CREATE TABLE `categoria` (
  `CATID` int(11) NOT NULL AUTO_INCREMENT,
  `CATIPO` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`CATID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `datospersonales` (
  `DATID` int(11) NOT NULL AUTO_INCREMENT,
  `USUID` int(11) DEFAULT NULL,
  `DATNOMBRE` varchar(50) DEFAULT NULL,
  `DATAPELLIDO` varchar(50) DEFAULT NULL,
  `DATIPOID` varchar(20) DEFAULT NULL,
  `DATNUMEROID` varchar(20) DEFAULT NULL,
  `DATELEFONO` varchar(20) DEFAULT NULL,
  `DATCORREO` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`DATID`),
  KEY `FK_RELATIONSHIP_1` (`USUID`),
  CONSTRAINT `FK_RELATIONSHIP_1` FOREIGN KEY (`USUID`) REFERENCES `usuario` (`USUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `rol` (
  `ROLID` int(11) NOT NULL AUTO_INCREMENT,
  `ROLTIPO` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ROLID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `usuario` (
  `USUID` int(11) NOT NULL AUTO_INCREMENT,
  `USULOGIN` varchar(20) DEFAULT NULL unique,
  `USUPASSWORD` varchar(20) DEFAULT NULL unique,
  PRIMARY KEY (`USUID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `usuario_rol` (
  `ROLID` int(11) NOT NULL,
  `USUID` int(11) NOT NULL,
  PRIMARY KEY (`ROLID`,`USUID`),
  KEY `FK_RELATIONSHIP_2` (`USUID`),
  CONSTRAINT `FK_RELATIONSHIP_2` FOREIGN KEY (`USUID`) REFERENCES `usuario` (`USUID`),
  CONSTRAINT `FK_RELATIONSHIP_3` FOREIGN KEY (`ROLID`) REFERENCES `rol` (`ROLID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `vehiculo` (
  `VEHPLACA` varchar(10) NOT NULL,
  `DATID` int(11) DEFAULT NULL,
  `CATID` int(11) DEFAULT NULL,
  `VEHMODELO` int(11) DEFAULT NULL,
  `VEHMARCA` varchar(50) DEFAULT NULL,
  `VEHESTADO` varchar(30) DEFAULT NULL,
  `VEHPRECIO` int(11) DEFAULT NULL,
  PRIMARY KEY (`VEHPLACA`),
  KEY `FK_REFERENCE_5` (`CATID`),
  KEY `FK_REFERENCE_6` (`DATID`),
  CONSTRAINT `FK_REFERENCE_5` FOREIGN KEY (`CATID`) REFERENCES `categoria` (`CATID`),
  CONSTRAINT `FK_REFERENCE_6` FOREIGN KEY (`DATID`) REFERENCES `datospersonales` (`DATID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


insert rol values (default,"Administrador"),
(default,"Comprador"),
(default,"Vendedor");
